Web-1021, pipelines use reusable workflow
monovomedical/reusable-github-workflows pull request #2
Opened 2022-02-23 21:44 UTC by jcdansie

A reusable workflow was created for deploying an existing build to production. This workflow is now being used by the production deployment pipeline in MCP. Connected code changes can be found in this pull request.

2022-02-23 22:17 UTC, dave-brandt7 commented
Nice work @jcdansie! Can we change the name of the script to something like `angular-cloudfront-version-deploy.yml`?

2022-02-23 22:17 UTC, dave-brandt7 requested changes
Nice work @jcdansie! Can we change the name of the script to something like angular-cloudfront-version-deploy.yml?

2022-02-23 23:00 UTC, dave-brandt7 approved these changes

2022-02-24 17:30 UTC, tthoang9 approved these changes

2022-02-24 20:12 UTC, franmah approved these changes

2022-02-25 17:53 UTC, merged